# Generated by Django 6.0.5 on 2026-06-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artistico', models.CharField(max_length=50, verbose_name='Nome de Jogo')),
                ('foto_rosto', models.ImageField(blank=True, help_text='Dê preferência a uma foto de rosto com fundo neutro', null=True, upload_to='perfil/', verbose_name='Foto de Perfil (Rosto)')),
                ('posicao', models.CharField(choices=[('ATA', 'Atacante'), ('MEI', 'Meio-Campo'), ('VOL', 'Volante'), ('LAT', 'Lateral'), ('ZAG', 'Zagueiro'), ('GOL', 'Goleiro')], max_length=3, verbose_name='Posição')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (ex: 1.75)')),
                ('pe_dominante', models.CharField(choices=[('D', 'Destro'), ('C', 'Canhoto')], max_length=10, verbose_name='Pé Dominante')),
                ('link_video', models.URLField(blank=True, null=True, verbose_name='Link do Vídeo (YouTube)')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram (sem @)')),
                ('whatsapp', models.CharField(help_text='Ex: 21970088404', max_length=20, verbose_name='WhatsApp (com DDD)')),
                ('visao_jogo', models.IntegerField(default=80, verbose_name='Visão de Jogo (0-100)')),
                ('precisao_passe', models.IntegerField(default=80, verbose_name='Precisão de Passe (0-100)')),
                ('controle_bola', models.IntegerField(default=80, verbose_name='Controle de Bola (0-100)')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Foto de Ação')),
                ('legenda', models.CharField(blank=True, max_length=100, verbose_name='Legenda (ex: Jogo na Barra)')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clube', models.CharField(max_length=100, verbose_name='Nome do Clube')),
                ('ano_inicio', models.IntegerField(verbose_name='Ano de Início')),
                ('ano_fim', models.CharField(help_text="Ex: 2023 ou 'Atual'", max_length=20, verbose_name='Ano de Fim')),
                ('conquistas', models.CharField(blank=True, max_length=255, verbose_name='Principais Títulos/Destaques')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='core.atleta')),
            ],
            options={
                'verbose_name': 'Histórico de Clube',
                'verbose_name_plural': 'Histórico de Clubes',
                'ordering': ['-ano_inicio'],
            },
        ),
    ]
