# Generated by Django 6.0.4 on 2026-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artistico', models.CharField(max_length=50, verbose_name='Nome de Jogo')),
                ('posicao', models.CharField(choices=[('ATA', 'Atacante'), ('MEI', 'Meio-Campo'), ('VOL', 'Volante'), ('LAT', 'Lateral'), ('ZAG', 'Zagueiro'), ('GOL', 'Goleiro')], max_length=3, verbose_name='Posição')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (ex: 1.75)')),
                ('pe_dominante', models.CharField(choices=[('D', 'Destro'), ('C', 'Canhoto')], max_length=10, verbose_name='Pé Dominante')),
                ('link_video', models.URLField(verbose_name='Link do Vídeo (YouTube)')),
            ],
        ),
    ]
