# Generated by Django 5.1.6 on 2026-08-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='cavarinha',
            field=models.IntegerField(default=70, verbose_name='Cavarinha (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='defesa',
            field=models.IntegerField(default=60, verbose_name='Defesa (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='disputa_aerea',
            field=models.IntegerField(default=55, verbose_name='Disputa Aérea (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='dribles',
            field=models.IntegerField(default=70, verbose_name='Dribles (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='finalizacao',
            field=models.IntegerField(default=65, verbose_name='Finalização (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='fisico',
            field=models.IntegerField(default=75, verbose_name='Físico (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='velocidade',
            field=models.IntegerField(default=75, verbose_name='Velocidade (0-100)'),
        ),
    ]
