# Generated by Django 6.0.4 on 2026-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instagram (sem @)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='whatsapp',
            field=models.CharField(default='', help_text='Ex: 21999999999', max_length=20, verbose_name='WhatsApp (com DDD)'),
            preserve_default=False,
        ),
    ]
