# Generated by Django 5.1.6 on 2026-08-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atleta_cavarinha_atleta_defesa_atleta_disputa_aerea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='foto_capa',
            field=models.ImageField(blank=True, help_text='Foto de ação para o fundo do Hero (recomendado: 1920x1080)', null=True, upload_to='capa/', verbose_name='Foto de Capa (Hero)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='sobre_mim',
            field=models.TextField(blank=True, default='Meio-campista ambidestro clássico com excelente leitura de jogo e capacidade de organização.', help_text="Texto pessoal que aparece na seção 'Sobre Mim'", verbose_name='Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='foto_rosto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de Perfil (Rosto)'),
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Nome do Autor')),
                ('cargo', models.CharField(blank=True, help_text='Ex: Treinador, Companheiro de Time', max_length=100, verbose_name='Cargo/Função')),
                ('texto', models.TextField(verbose_name='Depoimento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/', verbose_name='Foto do Autor')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos', to='core.atleta')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2025', max_length=4, verbose_name='Temporada')),
                ('gols', models.IntegerField(default=0, verbose_name='Gols')),
                ('assistencias', models.IntegerField(default=0, verbose_name='Assistências')),
                ('jogos', models.IntegerField(default=0, verbose_name='Jogos')),
                ('minutos', models.IntegerField(default=0, verbose_name='Minutos em Campo')),
                ('cartoes_amarelos', models.IntegerField(default=0, verbose_name='Cartões Amarelos')),
                ('cartoes_vermelhos', models.IntegerField(default=0, verbose_name='Cartões Vermelhos')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='core.atleta')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['-temporada'],
            },
        ),
    ]
