# Generated by Django 6.0.4 on 2026-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atleta_instagram_atleta_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='controle_bola',
            field=models.IntegerField(default=80, verbose_name='Controle de Bola (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='precisao_passe',
            field=models.IntegerField(default=80, verbose_name='Precisão de Passe (0-100)'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='visao_jogo',
            field=models.IntegerField(default=80, verbose_name='Visão de Jogo (0-100)'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='whatsapp',
            field=models.CharField(help_text='Ex: 21970088404', max_length=20, verbose_name='WhatsApp (com DDD)'),
        ),
    ]
