# Generated by Django 6.0.4 on 2026-04-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atleta_controle_bola_atleta_precisao_passe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Foto de Ação')),
                ('legenda', models.CharField(blank=True, max_length=100, verbose_name='Legenda (ex: Jogo na Barra)')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.atleta')),
            ],
        ),
    ]
