# Generated by Django 6.0.4 on 2026-04-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clube', models.CharField(max_length=100, verbose_name='Nome do Clube')),
                ('ano_inicio', models.IntegerField(verbose_name='Ano de Início')),
                ('ano_fim', models.CharField(help_text="Ex: 2023 ou 'Atual'", max_length=20, verbose_name='Ano de Fim')),
                ('conquistas', models.CharField(blank=True, max_length=255, verbose_name='Principais Títulos/Destaques')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='core.atleta')),
            ],
            options={
                'verbose_name': 'Histórico de Clube',
                'verbose_name_plural': 'Histórico de Clubes',
                'ordering': ['-ano_inicio'],
            },
        ),
    ]
