# Generated by Django 6.0.4 on 2026-04-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_atleta_link_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Dê preferência a uma foto de rosto com fundo neutro', null=True, upload_to='perfil/', verbose_name='Foto de Perfil (Rosto)'),
        ),
    ]
