# Generated by Django 6.0.4 on 2026-04-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_atleta_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atleta',
            old_name='foto_perfil',
            new_name='foto_rosto',
        ),
    ]
